create table if not exists public."HNtop30" (
  id bigint generated by default as identity primary key,
  story_id bigint not null,
  url text not null unique,
  title text not null,
  score integer not null default 0,
  descendants integer not null default 0,
  engagement_score integer not null default 0,
  discussion_ratio numeric(10, 2) not null default 0,
  value_label text not null default '均衡',
  author text not null default 'unknown',
  domain text not null default 'news.ycombinator.com',
  story_time timestamptz not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  is_current boolean not null default true,
  collected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_hntop30_story_time
  on public."HNtop30" (story_time desc);

create index if not exists idx_hntop30_is_current
  on public."HNtop30" (is_current, engagement_score desc);

create or replace function public.set_hntop30_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_hntop30_set_updated_at on public."HNtop30";

create trigger trg_hntop30_set_updated_at
before update on public."HNtop30"
for each row
execute function public.set_hntop30_updated_at();
